version: '3.9'
services:
  postgres-database:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: fia913kasd95123
      POSTGRES_DB: nuc-db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:

