name: Variables Print

on:
  workflow_dispatch:

env:
  LOCAL_ENV: Ahoj
  TEST_ENV: ${{ env.MY_ENVIRONMENT_VARIABLE }}

jobs:
  run-tests:
    name: 'Test'
    runs-on: [self-hosted, nuc-runner]
    steps:
      - name: Print
        run: | 
          echo "Hodnota env 1: ${{ vars.MY_ENVIRONMENT_VARIABLE }}"
          echo "Hodnota env 2: ${{ env.MY_ENVIRONMENT_VARIABLE }}"
          echo "Hodnota env 2: $TEST_ENV"
          echo "Local: $LOCAL_ENV"
